apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
    - name: kafka-client
      image: confluentinc/cp-enterprise-kafka:6.1.0
      volumeMounts:
        - mountPath: /kafka-client-storage
          name: kafka-client-storage
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"
  volumes:
    - name: kafka-client-storage